version: '3'

services:
  spark:
    image: xmuller/custom_spark
    hostname: sparkmaster
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_PID_DIR=/myTemp
      - SPARK_LOCAL_DIRS=/myTemp
    ports:
      - '8080:8080'
      - '8889:8889'
    volumes:
      - /c/FIIT/VI/vyhladavanie_spark/vyhladavanie_informacii:/data
      - /c/FIIT/VI/tmp-volumes/worker2:/myTemp
  spark-worker-1:
    image: xmuller/custom_spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_PID_DIR=/myTemp
      - SPARK_LOCAL_DIRS=/myTemp
    volumes:
      - /c/FIIT/VI/vyhladavanie_spark/vyhladavanie_informacii:/data
      - /c/FIIT/VI/tmp-volumes/master:/myTemp
  spark-worker-2:
    image: xmuller/custom_spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_PID_DIR=/myTemp
      - SPARK_LOCAL_DIRS=/myTemp
    volumes:
      - /c/FIIT/VI/vyhladavanie_spark/vyhladavanie_informacii:/data
      - /c/FIIT/VI/tmp-volumes/master:/myTemp
